### ISSUE TITLE
Error building the Elasticsearch index

### ISSUE THREAD

**Issue by oskasf** [kermitt2/biblio-glutton#100]
I am having some issues in trying to create the elastic search index for my CrossRef dump. I have setup an ElasticSearch container using docker and downloaded the CrossRef dump from academic torrents. After following the instructions in indexing/Readme I run `node main -dump "/home/oskafentem/April 2024 Public Data File from Crossref" index` but this results in the following error:

```
Crossref" index

action:   index
 
 Index crossref have been created
 
 total of 26810 files to be indexed
 
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at parseJson (/home/oskafentem/Documents/Github/biblio-glutton/indexing/main.js:192:24)
    at createBiblObj (/home/oskafentem/Documents/Github/biblio-glutton/indexing/main.js:221:12)
    at wrappedMapper (/home/oskafentem/Documents/Github/biblio-glutton/indexing/node_modules/map-stream/index.js:83:19)
    at Stream.stream.write (/home/oskafentem/Documents/Github/biblio-glutton/indexing/node_modules/map-stream/index.js:95:21)
    at Stream.ondata (internal/streams/legacy.js:20:31)
    at Stream.emit (events.js:400:28)
    at drain (/home/oskafentem/Documents/Github/biblio-glutton/indexing/node_modules/through/index.js:36:16)
    at Stream.stream.queue.stream.push (/home/oskafentem/Documents/Github/biblio-glutton/indexing/node_modules/through/index.js:45:5)
    at emit (/home/oskafentem/Documents/Github/biblio-glutton/indexing/node_modules/split/index.js:37:14)
Error occurred: TypeError: Cannot use 'in' operator to search for '_id' in null
Error when reading file TypeError: Cannot use 'in' operator to search for '_id' in null
    at createBiblObj (/home/oskafentem/Documents/Github/biblio-glutton/indexing/main.js:225:15)
    at wrappedMapper (/home/oskafentem/Documents/Github/biblio-glutton/indexing/node_modules/map-stream/index.js:83:19)
    at Stream.stream.write (/home/oskafentem/Documents/Github/biblio-glutton/indexing/node_modules/map-stream/index.js:95:21)
    at Stream.ondata (internal/streams/legacy.js:20:31)
    at Stream.emit (events.js:400:28)
    at drain (/home/oskafentem/Documents/Github/biblio-glutton/indexing/node_modules/through/index.js:36:16)
    at Stream.stream.queue.stream.push (/home/oskafentem/Documents/Github/biblio-glutton/indexing/node_modules/through/index.js:45:5)
    at emit (/home/oskafentem/Documents/Github/biblio-glutton/indexing/node_modules/split/index.js:37:14)
    at next (/home/oskafentem/Documents/Github/biblio-glutton/indexing/node_modules/split/index.js:49:7)
    at Stream.<anonymous> (/home/oskafentem/Documents/Github/biblio-glutton/indexing/node_modules/split/index.js:54:5)
(node:7334) UnhandledPromiseRejectionWarning: TypeError: Cannot use 'in' operator to search for '_id' in null
    at createBiblObj (/home/oskafentem/Documents/Github/biblio-glutton/indexing/main.js:225:15)
    at wrappedMapper (/home/oskafentem/Documents/Github/biblio-glutton/indexing/node_modules/map-stream/index.js:83:19)
    at Stream.stream.write (/home/oskafentem/Documents/Github/biblio-glutton/indexing/node_modules/map-stream/index.js:95:21)
    at Stream.ondata (internal/streams/legacy.js:20:31)
    at Stream.emit (events.js:400:28)
    at drain (/home/oskafentem/Documents/Github/biblio-glutton/indexing/node_modules/through/index.js:36:16)
    at Stream.stream.queue.stream.push (/home/oskafentem/Documents/Github/biblio-glutton/indexing/node_modules/through/index.js:45:5)
    at emit (/home/oskafentem/Documents/Github/biblio-glutton/indexing/node_modules/split/index.js:37:14)
    at next (/home/oskafentem/Documents/Github/biblio-glutton/indexing/node_modules/split/index.js:49:7)
    at Stream.<anonymous> (/home/oskafentem/Documents/Github/biblio-glutton/indexing/node_modules/split/index.js:54:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7334) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7334) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
 
All tasks completed !
 
Execution time: 1047ms
```

I thought that this issue might be due to using the latest version of the data dump, however, I run into the same problem for the 2022 CrossRef version. 

I am not a javascript user so perhaps I am missing something simple here. I did verify that the files contain valid json, by unzipping and reading into Python which works fine. 

Any help on this issue would be greatly appreciated, apologies if I am overlooking something very simple!

**Comment by lfoppiano** [comment]
Hi @oskasf, you need to use the master version for loading the 2024 dump, and since the last update all the indexing and data loading is done by a single command, please check [here](https://biblio-glutton.readthedocs.io/en/latest/Build-Databases/).

**Comment by oskasf** [comment]
Ah I see, so sorry for my mistake here! 

On closer inspection though it does seem that there aren't any records that get loaded to elasticsearch. If I run `http://localhost:9200/crossrefdata/_count?pretty` then it seems like there are 0 records that have been recorded:

```
{
"count": 0,
"_shards": {
"total": 1,
"successful": 1,
"skipped": 0,
"failed": 0
}
}
```

When running the above command you suggested I change the glutton.yml config so that it points to the correct elasticsearch host. Sorry I think I am probably missing something very stupid here!

**Comment by lfoppiano** [comment]
There are two storages: the elasticsearch which contains only the crossref dump information (used for querying by title, etc...) and the datastorage, which contains the mappings. 

from the JSON you loaded correctly the crossref dump in both the datastore and the index: 

```
"Crossref Metadata stored size": "{crossref_Jsondoc=149817829}",
"Total metadata indexed size": "{crossref_Jsondoc=149817829}",
```

When you run the PMID mapping it will load them only in the datastore (there is no need for them to be in the index). 

I'm not sure about your configuration, though, by default the index is called `glutton`, unless you've changed the name.

**Comment by oskasf** [comment]
Thanks for your explanation!

Yes I did change the name in the glutton.yml. 

Perhaps I shouldn't have used PMID as an example here, but what I was trying to illustrate is that I am only able to query the data using DOIs. Any query which doesn't contain a DOI isn't able to retrieve a record and I get a 400 error.

**Comment by lfoppiano** [comment]
It's likely a problem with the connection to elasticsearch. I'm surprised that you got the 148M rows from the index 🤔 

OK... there is a bug in the code or something: 

```
       returnMap.put("Crossref Metadata stored size", String.valueOf(crossrefMetadataLookup.getSize()));
        returnMap.put("HAL Metadata stored size", String.valueOf(halLookup.getSize()));
        returnMap.put("Total metadata indexed size", String.valueOf(metadataMatching.getSize()));
```

Can you change branch `fix-metadata-size-display`: 

```
git checkout fix-metadata-size-display
```

and run it again? Assuming you're not using docker for biblio-glutton (not recommended at the moment)

**Comment by oskasf** [comment]
Ah yes if I do this it shows:

```
"Total metadata indexed size": "{crossrefdata=0}"
```

but the CrossRef metadata size is correct.

**Comment by lfoppiano** [comment]
OK. is elasticsearch accessible without any problem? 


It's probably useless, what does this command returns? 

```
curl 'localhost:9200/_cat/indices?v'
```

**Comment by oskasf** [comment]
Yes it seems like it is accessible:

```
health status index        uuid                   pri rep docs.count docs.deleted store.size pri.store.size dataset.size
green  open   crossrefdata sTz5d5BaQQ-wajeasujghw   1   0          0            0       249b           249b         249b
```

**Comment by lfoppiano** [comment]
I think, you should move or delete the `data/db/crossref` and reindex the crossref dump.

**Comment by oskasf** [comment]
Just tested it with a couple of `json.gz` files and seems to be working now. Sorry I think I must've messed something up with my elasticsearch setup initially, thanks so much for your help and patience in diagnosing this!

**Comment by lfoppiano** [comment]
That's great! 👍
