### ISSUE TITLE
Run path for gap/daily sync with Crossref

### ISSUE THREAD

**Issue by kermitt2** [kermitt2/biblio-glutton#74]
from @Aazhar 
Currently the service has to be launched from the `biblio-glutton/lookup` repertory to solve the path to the indexing for daily update, otherwise:

```
ERROR [2022-04-27 03:14:12,161] com.scienceminer.lookup.utils.crossrefclient.IncrementalLoaderTask: IO error when executing external command: [node, main, -dump, /opt/biblio-glutton/crossref_increments/2022-04-26/D1000310.json.gz, extend]
! java.io.IOException: error=2, No such file or directory
! at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
! at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
! at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
! at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
! ... 7 common frames omitted
! Causing: java.io.IOException: Cannot run program "node" (in directory "../indexing"): error=2, No such file or directory
```

We could improve the resolution of the path, probably with an optional install path parameter.

**Comment by karatekaneen** [comment]
@kermitt2 Unfortunately I don't know enough Java to figure out how to load the path in a smarter way, but if interested I can open a PR changing it to "../../indexing" to allow it to work in the Docker image?

Also, do you know if the files already downloaded but not indexed will get indexed when this is fixed or are they already "processed"? If so, is it possible to reset somehow?
